version: '3.7'
services: 
  app: 
    container_name: unimore-trading-time-and-attendance-payroll
    restart: always
    build: .
    ports: 
      - '8081:5001'
    # links: 
    networks: 
      - appnet
    links: 
      - mongodb
    depends_on: 
      - mongodb
    environment:
      TZ: "Asia/Manila"
  mongodb: 
    container_name: mongodb
    restart: always
    image: mongo
    ports: 
      - '27018:27017'
    networks: 
      - appnet
    volumes:
      - db-data:/data/db
    environment:
      TZ: "Asia/Manila"
networks: 
  appnet: 
    driver: bridge
volumes: 
  db-data: