version: '3'
services: 
  app: 
    container_name: unimore-trading-time-and-attendance-payroll
    restart: always
    build: .
    ports: 
      - '8081:5001'
    # links: 
    networks: 
      - mern-app
    depends_on: 
      - mongo
    environment:
      TZ: "Asia/Manila"
  mongo: 
    container_name: mongo-payroll
    restart: always
    image: mongo
    ports: 
      - '27027:27017'
    networks: 
      - mern-app
    volumes:
      - mongo-payroll-data:/data/db
    environment:
      TZ: "Asia/Manila"
networks: 
  mern-app: 
    driver: bridge
volumes: 
  mongo-payroll-data: