version: '3'
services: 
  app: 
    container_name: unimore-trading-ta
    restart: always
    build: .
    ports: 
      - '8080:5000'
    links: 
      - mongo
  mongo: 
    container_name: mongo
    restart: always
    image: mongo
    ports: 
      - '27017:27017'